# Generated by Django 4.2.19 on 2025-03-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('organization', 'Organization'), ('jobseeker', 'Job Seeker')], max_length=20),
        ),
    ]
